### ISSUE TITLE
Umlaute in slugs richtig umschreiben

### ISSUE THREAD

**Issue by philipsteffan** [okfde/jh-lauch-theme#1]
"Köln" in einem Titel wird zu "koln" in der URL, nicht "koeln".

In meiner Erinnerung kann Wordpress das aber – ich weiß leider nicht, ob das von der eingestellten Lokalisationsdatei erledigt wird oder ob ich in der Vergangenheit immer "vorgepatchte" deutsche WP-Installationen benutzt habe. Unsere bisherige JH-Seite kann es, offenbar ohne Plugin.

[hier ein codeschnipsel](https://gist.github.com/davidsneighbour/9c6e1eb93d110b4bf59b)

**Comment by lislis** [comment]
Kann tatsächlich sein, dass ein deutsch lokalisiertes Wordpress sich da anders verhält. Ich behalte das im Auge und verwende ggf Schnipsel aus dem gist

**Comment by lislis** [comment]
ich mach mal zu, sag wenn das immer noch ein problem ist in der deutschen locale
