### ISSUE TITLE
Was machen die zwei Parameter?

### ISSUE THREAD

**Issue by philipsteffan** [okfde/jh-lauch-theme#106]
Hi @vellip - ich würde gern den Drehwinkel verkleinern, bekomm das auch mit den zwei Zahlen hin, verstehe aber leider nicht, was sie genau bedeuten – was bewirken die Werte 16 und 8 genau?

https://github.com/okfde/jh-lauch-theme/blob/e2000731a249d2a617f13ede6474cd9b8d14081f/js/main.min.js#L25

**Comment by vellip** [comment]
Hey @philipsteffan
das muss [hier](https://github.com/okfde/jh-lauch-theme/blob/master/static-prototype/assets/js/main.js#L368) geändert werden. Und dann entsprechend wie [hier](https://github.com/okfde/jh-lauch-theme/blob/master/static-prototype/README.md) beschrieben, generiert werden. 

Im ersten Link über der Funktion ist auch die getRandom Funktion. Das erste ist der Maximalwert, das zweite der Minimalwert (falls nicht angegeben = 0).

**Comment by vellip** [comment]
Also in dem oberen Fall nimmt es eine zufällige Drehung zwischen 8-16 Grad.

**Comment by philipsteffan** [comment]
Danke!
Wenn ich das im Kopf durchrechne, dann müsste (16,8) dafür sorgen, dass am Ende ein Winkel zwischen -7 und 15 rauskommt - oder versteh ich den Term falsch? Ist aber auch nicht so wichtig, es klappt ja auch experimentell, wenn ich die Zahlen so verkleinere, dass mir das Ergebnis gefällt :)

**Comment by vellip** [comment]
Das ist dann einfach ein WInkel zw. 8 und 16. Wenn man negative Winkel mag, muss man das auch angeben.
Ja genau, so geht das auch. :D
