### ISSUE TITLE
anmelden button + banner zu aktuellem event auf event rueckblick

### ISSUE THREAD

**Issue by lislis** [okfde/jh-lauch-theme#64]

**Comment by michamilz** [comment]
Das ist doch fertig, oder?
Soll der Link zur Anmeldung direkt zur Anmeldung springen?

**Comment by lislis** [comment]
@michamilz das ist was anderes. Das Banner erscheint gerade nur auf den aktuellen Event-Seiten. Die Idee hier ist, dass die Rückblicke wissen, ob in ihrer Stadt gerade ein aktuelles Event ansteht, und das dann anzuteasern. Quasi um noch einen Punkt zu haben, potentielle Teilnehmis abzuholen

**Comment by lislis** [comment]
done
